name: Mutual Fund Alert

on:
  schedule:
    - cron: "30 15 * * 1-5"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: mutual-fund-alert
  cancel-in-progress: false

jobs:
  run-mf-alert:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r mf_alert_app/requirements.txt

      - name: Run mutual fund script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python mf_alert_app/main.py

      - name: Check output
        run: |
          ls -lh mf_alert_app/output.csv

      - name: Commit output
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
          git add mf_alert_app/output.csv
      
          git diff --cached --quiet || git commit -m "Update mutual fund output"
      
          git pull --rebase origin main
      
          git push origin main
